### ISSUE TITLE
BigQuery TypeError: connect() got an unexpected keyword argument 'database'

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#1860]
I installed using `pip install ibis-framework[bigquery] vdsql` on  python 3.8 on WSL.

Connecting with `vdsql bigquery:///my-project-name` resulted in a listing of all the datasets within the project. So far so good.

Upon highlighting a dataset, I got the error: `TypeError: connect() got an unexpected keyword argument 'database'`

Installing using `pip install git+https://github.com/visidata/vdsql.git` results in the same outcome.

Is there a specific version of `ibis-framework` I should be forcing?

**Comment by anjakefala** [comment]
@dougscc Yes! 

This should work with `ibis-framework` 3.2.0. If you are still having trouble with that, I would update to the `develop` version of https://github.com/ibis-project/ibis

`pip install git+https://github.com/ibis-project/ibis.git`. I am having trouble finding the precise version of `ibis-framework` where this API change happened.

I am going to try to reproduce. If you end up trying a precise version, and it solves the problem, could you please report back?

**Comment by ghost** [comment]
Attempted a full re-install and got:

` WARNING: ibis-framework 3.2.0 does not provide the extra 'bigquery'` which is unfortunate.

Is the bigquery extension gone?

Installing development version as described above did not change the error.

**Comment by lxcode** [comment]
@dougscc You need to install ibis-bigquery separately:

https://github.com/ibis-project/ibis-bigquery

**Comment by ghost** [comment]
@lxcode well, that was embarrassing. Still getting the `TypeError: connect() got an unexpected keyword argument 'database'`
error. I don't know enough to be a help vis. where the error originates. I did test the connection using `ibis-biquery`

```python
>>> import ibis
>>> ibis.options.interactive = True
>>> connection = ibis.bigquery.connect(project_id="foo-project", dataset_id="foo-project.dbt_dshawhan")
>>> foo = connection.table("foo_charges", database="foo-project.dbt_dshawhan")
```
which appears to work fine. If you have any other suggestions, I'm glad to try.

**Comment by lmmx** [comment]
Reproduces on Linux Python 3.10, `pip install vdsql ibis-framework[bigquery]` and had `gcloud` CLI configured, still get the error in the title of this issue. Likewise I see the datasets in the project but can't open them.

Likewise scratching my head how to debug this: have just searched all through the library for kwarg passing and can't see `database` being passed to `connect` anywhere...

- `ibis_bigquery` (v2.2.1) contains a call to `backend.connect()`once: no named `database` param and no `**kwargs` passing
- `ibis` (v3.2.0) has calls to `connect()` but again none I can see that calls an argument `database` or uses `**kwargs`

Also not sure how to catch the error in a debugger seen as how it's in a terminal GUI.

Actually tell a lie, I used `sudo memray attach $(pgrep vdsql)` and got a dump of the call stack which is better than nothing

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Location                                                                                                           ┃        <Total Memory> ┃        Total Memory % ┃            Own Memory ┃          Own Memory % ┃      Allocation Count ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩
│ mainloop at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/mainloop.py                               │              51.039KB │                 4.39% │                0.000B │                 0.00% │                    53 │
│ run at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/mainloop.py                                    │              51.039KB │                 4.39% │                0.000B │                 0.00% │                    53 │
│ wrappedfunc at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/extensible.py                          │              51.039KB │                 4.39% │                0.000B │                 0.00% │                    53 │
│ _vdfunc at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/vdobj.py                                   │              51.039KB │                 4.39% │                0.000B │                 0.00% │                    53 │
│ main_vd at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/main.py                                    │              51.039KB │                 4.39% │                0.000B │                 0.00% │                    53 │
│ vd_cli at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/main.py                                     │              51.039KB │                 4.39% │                0.000B │                 0.00% │                    53 │
│ main at /home/louis/miniconda3/lib/python3.10/site-packages/vdsql/__main__.py                                      │              51.039KB │                 4.39% │                0.000B │                 0.00% │                    53 │
│ <module> at /home/louis/miniconda3/bin/vdsql                                                                       │              51.039KB │                 4.39% │                0.000B │                 0.00% │                    53 │
│ newinit at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/extensible.py                              │              39.891KB │                 3.43% │                0.000B │                 0.00% │                    43 │
│ __init__ at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/sheets.py                                 │              39.891KB │                 3.43% │                0.000B │                 0.00% │                    43 │
│ execCommand at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/basesheet.py                           │              39.891KB │                 3.43% │                0.000B │                 0.00% │                    43 │
│ cmdlog at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/cmdlog.py                                   │              32.355KB │                 2.78% │                0.000B │                 0.00% │                    38 │
│ dofunc at /home/louis/miniconda3/lib/python3.10/site-packages/visidata/extensible.py                               │              32.355KB │                 2.78% │                0.000B │                 0.00% │                    38 
```

**Edit** OK I used a combo of `remote_pdb.set_trace(port=1234)` and `telnet 127.0.0.1 1234` to then call `traceback.print_exception(e, file=open("/home/louis/Downloads/exc_log.txt"))` to dump this traceback from visidata's `threads.py` module

```py
Traceback (most recent call last):
  File "/home/louis/miniconda3/lib/python3.10/site-packages/visidata/threads.py", line 234, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/louis/miniconda3/lib/python3.10/site-packages/visidata/sheets.py", line 290, in reload
    for r in self.iterload():
  File "/home/louis/miniconda3/lib/python3.10/site-packages/vdsql/_ibis.py", line 123, in iterload
    with self.con as con:
  File "/home/louis/miniconda3/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/louis/miniconda3/lib/python3.10/site-packages/vdsql/_ibis.py", line 95, in get_conn
    r = ibis.connect(str(self.source))
  File "/home/louis/miniconda3/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/louis/miniconda3/lib/python3.10/site-packages/ibis/backends/base/__init__.py", line 788, in _
    return _connect(url, **kwargs)
  File "/home/louis/miniconda3/lib/python3.10/site-packages/ibis/common/dispatch.py", line 104, in __call__
    return func(s, *args, **kwargs, **match.groupdict())
  File "/home/louis/miniconda3/lib/python3.10/site-packages/ibis/backends/base/__init__.py", line 726, in _
    return instance._from_url(url)
  File "/home/louis/miniconda3/lib/python3.10/site-packages/ibis/backends/base/sql/__init__.py", line 61, in _from_url
    return self.connect(**kwargs)
TypeError: Backend.connect() got an unexpected keyword argument 'database'
```

I suspected it might've been `_from_url` but the call path was too twisted to see how.

If we debug the penultimate call here at line 726 in `ibis.backends.base.__init__` we see that the `_from_url()` method call reaches an instance of the `ibis_bigquery.Backend` class which is introducing the culpable kwarg:

```py
> /home/louis/miniconda3/lib/python3.10/site-packages/ibis/backends/base/__init__.py(723)_()
-> return instance._from_url(url)
(Pdb) p url
'bigquery:///beatchain-prod-1566985681850/beatchain'
(Pdb) p instance
<ibis_bigquery.Backend object at 0x7f03d0d93940>
(Pdb) p type(instance)
<class 'ibis_bigquery.Backend'>
(Pdb) p type(instance).mro()
[<class 'ibis_bigquery.Backend'>, <class 'ibis.backends.base.sql.BaseSQLBackend'>, <class 'ibis.backends.base.BaseBackend'>, <class 'abc.ABC'>, <class 'object'>]
(Pdb) pp type(instance).mro()
[<class 'ibis_bigquery.Backend'>,
 <class 'ibis.backends.base.sql.BaseSQLBackend'>,
 <class 'ibis.backends.base.BaseBackend'>,
 <class 'abc.ABC'>,
 <class 'object'>]
```

but it's in fact because the `ibis_bigquery` package does not redefine the `_from_url` method, instead it is inherited from `ibis.backends.base.sql.BaseSQLBackend`:

```py
(Pdb) p instance._from_url
<bound method BaseSQLBackend._from_url of <ibis_bigquery.Backend object at 0x7f03d0d93940>>
```

We can see the `database` kwarg is created on the basis of what `sqlalchemy.engine.make_url` determines the `database` attribute of the URL to be:

```py
    def _from_url(self, url: str) -> BaseBackend:
        """Connect to a backend using a URL `url`.

        Parameters
        ----------
        url
            URL with which to connect to a backend.

        Returns
        -------
        BaseBackend
            A backend instance
        """
        url = sa.engine.make_url(url)

        kwargs = {
            name: value
            for name in ("host", "port", "database", "password")
            if (value := getattr(url, name, None))
        }
        if username := url.username:
            kwargs["user"] = username

        kwargs.update(url.query)
        self._convert_kwargs(kwargs)
        return self.connect(**kwargs)
```

`sqlalchemy.engine.make_url` is not at fault here: it's the assumption that kwargs named `("host", "port", "database", "password")` can be made and passed to the `Backend.connect()` method even though its function signature has none of these kwargs!

Note that there is the opportunity to intervene with this kwargs dict via definition of `self._convert_kwargs(kwargs)`. It is not defined on any of the inheriting classes here

```py
(Pdb) p instance._convert_kwargs
<function BaseBackend._convert_kwargs at 0x7f03d0e85480>
```

meaning it falls to the `ibis.backends.base.BaseBackend` definition, which is a no-op (empty stub):

```py
    def _convert_kwargs(kwargs: MutableMapping) -> None:
        """Manipulate keyword arguments to `.connect` method."""
```

So in conclusion we need the `ibis-bigquery` package to define `_from_url`

```py
    def _from_url(self, url: str) -> Backend:
        """Connect to a BigQuery backend using a URL `url`.

        Parameters
        ----------
        url
            URL with which to connect to a BigQuery backend.

        Returns
        -------
        Backend
            A BigQuery backend instance
        """
        url = sa.engine.make_url(url)
        project_id, _, dataset_id = url.database.partition("/")
        kwargs = dict(project_id=project_id, dataset_id=dataset_id)
        return self.connect(**kwargs)
```

After that I get the error

```py
AttributeError: 'IbisTableIndexSheet' object has no attribute 'sheet_type'
```

Seems to already be documented:

- #1865

Inspecting the code, this was a deprecation that was not updated elsewhere in the code: there is no longer a `sheet_type` attribute/property so this will always fail, and must be replaced for this to work. Specifically the `yield` statement of the `iterload()` method of the `IbisTableIndexSheet` class in `vdsql/_ibis.py`.

This is not fixed in the `develop` branch of either:

- `vdsql` repo: https://github.com/saulpw/vdsql/blob/21b43513700e305f4ee92bcfba88cf94d4a35243/vdsql/_ibis.py#L128
- `visidata` repo: https://github.com/saulpw/visidata/blob/925d75b7b5ba867fc226391e00d4ca3cdac4eace/visidata/apps/vdsql/_ibis.py#L128

It should be edited to:

```py
                yield IbisTableSheet(
```

With this fixed, the `vdsql` BigQuery integration works to show a project's dataset's tables! :tada:

**Comment by saulpw** [comment]
Wow, that's some advanced debugging, @lmmx!  The only thing is that `sheet_type` *is* used by the clickhouse and snowflake backends, so they can use their own custom child classes as they want.  `sheet_type` should be set to `IbisTableSheet` by default though, so I'm not sure why it's not for bigquery...

**Comment by lmmx** [comment]
Thanks Saul, yeah wasn't sure about that one, equally happy to set `sheet_type` as `IbisTableSheet` and leave the `yield` call as is. I looked into it further but it seems to be solved in the `0.3dev` version in this repo, so it's just a matter of waiting for another release I think

<details><summary>Click to show more details</summary>

I had a look and the way `sheet_type` is set seems to be

https://github.com/saulpw/visidata/blob/bf727938567076a7241c6225c962366c2f8be90e/visidata/sheets.py#L150

on `TableSheet` (which is aliased as `Sheet` as the base type for `IbisTableSheet`).

`IbisTableIndexSheet` is initialised for Clickhouse's `openurl_` global (which gets [used for the backend lookup](https://github.com/saulpw/visidata/blob/bf727938567076a7241c6225c962366c2f8be90e/visidata/_open.py#L81C1-L81C94) when handling the URL) with a kwarg named `sheet_type`, hence the `__dict__` update that sets the named attribute.

https://github.com/saulpw/visidata/blob/bf727938567076a7241c6225c962366c2f8be90e/visidata/apps/vdsql/clickhouse.py#L9-L12

Likewise `IbisTableIndexSheet` is initialised for Snowflake's `openurl_` global with a `sheet_type` kwarg

https://github.com/saulpw/visidata/blob/bf727938567076a7241c6225c962366c2f8be90e/visidata/apps/vdsql/snowflake.py#L9-L12

`IbisTableIndexSheet` is not in the `openurl_` global for the BigQuery backend handler, but instead `sheet_type` is set when initialising `IbisTableIndexSheet` in the `openRow()` method of the `BigqueryDatabaseIndexSheet` class.

https://github.com/saulpw/visidata/blob/bf727938567076a7241c6225c962366c2f8be90e/visidata/apps/vdsql/bigquery.py#L49-L56

I put a breakpoint in again on the `__init__` method of the `IbisTableIndexSheet` (specifically when I run `vdsql bigquery:///bigquery-public-data` and enter the `bbc_news` dataset) and it shows it's initialised with the kwargs:

```py
{'database_name': 'bigquery-public-data.bbc_news',
 'filetype': None,
 'ibis_con': <ibis_bigquery.Backend object at 0x7f3e2f16e890>,
 'ibis_conpool': <vdsql._ibis.IbisConnectionPool object at 0x7f3e2ef5c2b0>,
 'source': <google.cloud.bigquery.dataset.DatasetListItem object at 0x7f3e2f16ee30>}
```

The reason I couldn't see the problem was I was looking at the repo source which sets `sheet_type`!

My installed version of `vdsql` has an outdated definition of `openRow`, from the latest release (v0.2)

```py
    def openRow(self, row):
        return IbisTableIndexSheet(row.dataset_id,
                                   database_name=self.source.name+'.'+row.dataset_id,
                                   ibis_con=self.con,
                                   ibis_conpool=IbisConnectionPool(f"{self.source}/{row.dataset_id}"),
                                   source=row,
                                   filetype=None)
```

Confirmed that using the `0.3dev` version from the git repo and editing the `ibis_bigquery` package with the previously mentioned `_from_url` method is sufficient to fix this

```py
from __future__ import annotations

import sqlalchemy as sa
```

```py

    def _from_url(self, url: str) -> Backend:
        """Connect to a BigQuery backend using a URL `url`.

        Parameters
        ----------
        url
            URL with which to connect to a BigQuery backend.

        Returns
        -------
        Backend
            A BigQuery backend instance
        """
        url = sa.engine.make_url(url)
        project_id, _, dataset_id = url.database.partition("/")
        kwargs = dict(project_id=project_id, dataset_id=dataset_id)
        return self.connect(**kwargs)
```

</details>

Long story short I think this is actually a dependency issue: I somehow have `ibis-bigquery` but that GitHub repo is archived, and says to use `ibis.backends.bigquery`... I installed via `pip install ibis-framework[bigquery] vdsql[bigquery]` so I'm confused what went wrong...

Anyway there is a `_from_url` method on the BigQuery backend in that library, I'm just a bit confused how to get it rather than the deprecated backend...

In a fresh Python 3.10 env:

```
pip install visidata vdsql ibis-framework[bigquery]
```

installs `ibis_bigquery`:

```
Collecting visidata                                                                                                                                                                  
  Using cached visidata-2.11.1-py3-none-any.whl (330 kB)                                                                                                                             
Collecting vdsql                                                                                                                                                                     
  Using cached vdsql-0.2-py3-none-any.whl (21 kB)                                                                                                                                    
Collecting ibis-framework[bigquery]                                                                                                                                                  
  Using cached ibis_framework-6.0.0-py3-none-any.whl (1.5 MB)                                                                                                                        
...
Collecting ibis-bigquery (from vdsql)                                                                                                                                                
  Using cached ibis_bigquery-2.2.1-py3-none-any.whl (34 kB)    
```

and this contains the BQ backend without a `_from_url` method, causing the bug.

The `vdsql` repo has `ibis-bigquery` in [the requirements](https://github.com/saulpw/vdsql/blob/develop/requirements.txt)

The `vdsql` "app" (plugin?) has `ibis-framework[bigquery]` in [the requirements](https://github.com/saulpw/visidata/blob/develop/visidata/apps/vdsql/requirements.txt)

I think the README there is outdated though, it still says `pip install vdsql` to get the app...

https://github.com/saulpw/visidata/blob/bf727938567076a7241c6225c962366c2f8be90e/visidata/apps/vdsql/README.md?plain=1#L45

**Comment by saulpw** [comment]
Okay, so now we're using the more general `ibis.connect()` interface to create the connection for bigquery, which should be able to just take a bigquery URL:
```
vdsql bigquery://<billing_project>/<project_id>
```
For instance, to use the `bigquery-public-data` project, I created a billing project named `visidata`, and had to access it like:

```
vdsql bigquery://visidata/bigquery-public-data
```

Otherwise, without the billing project, you'll be able to list the datasets, but not actually launch any "jobs" to access the data.  But this seems to work cleanly now!
