### ISSUE TITLE
`visidata` since commit `260b685` crashes with `AttributeError: 'VisiData' object has no attribute 'numTimeouts'`

### ISSUE THREAD

**Issue by iamleot** [saulpw/visidata#2914]
**Small description**

Since commit 260b6851e8bd4e4ee00d21abffd6803c69bfa944 `visidata` crashes with:

```
AttributeError: 'VisiData' object has no attribute 'numTimeouts'
```

After a `git bisect` I have seen that the last working commit is bcc565e3a20abfd50d29ad4508c20815617217d6.

**Data to reproduce**

N/A

**Steps to reproduce**

Assuming that we are inside the root directory of `visidata` repository:

```shell
python3 -m visidata
```

**Expected result**

visidata starting without any traceback.

**Actual result with screenshot**

Here the complete traceback:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ".../visidata/visidata/__main__.py", line 3, in <module>
    vd_cli()
  File ".../visidata/visidata/main.py", line 392, in vd_cli
    rc = main_vd()
  File ".../visidata/visidata/main.py", line 350, in main_vd
    run(vd.sheets[0])
  File ".../visidata/visidata/vdobj.py", line 34, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
  File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File ".../visidata/visidata/mainloop.py", line 341, in run
    scr = vd.initCurses()
  File ".../visidata/visidata/extensible.py", line 80, in wrappedfunc
    r = oldfunc(*args, **kwargs)
  File ".../visidata/visidata/mainloop.py", line 314, in initCurses
    vd.drainPendingKeys(scr)
  File ".../visidata/visidata/vdobj.py", line 137, in drainPendingKeys
    scr.timeout(self.get_curses_timeout())
  File ".../visidata/visidata/mainloop.py", line 284, in get_curses_timeout
    vd.numTimeouts += 1
AttributeError: 'VisiData' object has no attribute 'numTimeouts'
```

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?
  Yes.

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?
  Yes, tested with commit cc99e73718e45ae1b0ef706500742b22bbf9ff2e that is the latest one at the time of writing this issue.

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?
  NetBSD/amd64

- Which version of Python?
  3.13.10

- Which terminal are you using (for display and input issues)?
  st and tmux with `tmux-256color` as `$TERM`

**Comment by iamleot** [comment]
This was noticed while trying to test #2913.

**Comment by iamleot** [comment]
According the traceback it seems that `mainloop()` was never called. I have validated this hypthesis by also putting a `breakpoint()` in `mainloop()` and see that it is never triggered and so the execution ends up with the same traceback.
