### ISSUE TITLE
[develop-branch] Traceback in pivot

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#316]
Seeing this error when doing a pivot:
Traceback (most recent call last):
  File "...site-packages/visidata/threads.py", line 191, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "...site-packages/visidata/pivot.py", line 125, in addAggregateCols
    aggname = aggregator.__name__
AttributeError: 'list' object has no attribute '__name__'

Didn't have a chance to debug.

**Comment by anjakefala** [comment]
Good catch!

The bug has to do with doing a pivot, when there are no set aggregators.

It was introduced with this commit:  https://github.com/saulpw/visidata/commit/5b8b4691e44ef15026c15d49a64916132677e9d1

**Comment by anjakefala** [comment]
We decided to revert the offending change for now and added a regression test. I appreciate you keeping an eye on develop and noting problems. =)
