### PR TITLE
[mouse-] call curses.mousemask() only if available

### PR DESCRIPTION
**Pull request by iamleot**
`curses.mousemask()` is not available in all `curses(3)` implementations (for example in NetBSD `curses(3)`).

Call it only if available.

Related to PR #2851.

- [ ] If contributing a core loader, [the loader checklist](https://visidata.org/docs/contributing#loader) was referenced.
- [ ] If registering an external plugin, [the plugin checklist](https://visidata.org/docs/contributing#plugins) was referenced.

---

To reproduce it, in NetBSD:

```
$ cat <<EOF >/tmp/repro.csv
one,two,three
1,2,3
EOF
$ cat /tmp/repro.csv
one,two,three
1,2,3
$ python3 -m visidata /tmp/repro.csv
```

...and then once `visidata` is opened just pressing `e` is enough to trigger it and the corresponding stack trace is:

```
Traceback (most recent call last):
  File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File ".../visidata/visidata/mainloop.py", line 231, in mainloop
    sheet.execCommand(vd.bindkeys._get(vd.keystrokes), keystrokes=vd.keystrokes)
  File ".../visidata/visidata/extensible.py", line 80, in wrappedfunc
    r = oldfunc(*args, **kwargs)
  File ".../visidata/visidata/basesheet.py", line 218, in execCommand
    escaped = self.execCommand2(cmd, vdglobals=vdglobals)
  File ".../visidata/visidata/extensible.py", line 80, in wrappedfunc
    r = oldfunc(*args, **kwargs)
  File ".../visidata/visidata/basesheet.py", line 82, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "edit-cell", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
  File ".../visidata/visidata/_input.py", line 688, in editCell
    r = vd.editText(y, x, w, attr=colors.color_edit_cell, **editargs)
  File ".../visidata/visidata/_input.py", line 397, in editText
    v = widget.editline(vd.activeSheet._scr, y, x, w, attr=attr, updater=updater, bindings=bindings, clear=clear)
  File ".../visidata/visidata/_input.py", line 179, in editline
    with EnableCursor():
  File ".../visidata/visidata/_input.py", line 63, in __enter__
    curses.mousemask(0)
AttributeError: module 'curses' has no attribute 'mousemask'
```

### CODE REVIEW

**Comment by iamleot** [comment]
To elaborate a bit more what was written in #2851. AFAIK mouse is an extension to POSIX curses(3) and hence `curses.mousemask()` could be not available.

FreeBSD and OpenBSD uses ncurses so they are probably not affected.

**Comment by saulpw** [comment]
Thanks, @iamleot.  I decided to factor the mousemask check and call into a vd.enableMouse() function to handle it.  Please let me know if this does or doesn't fix the issue for NetBSD.

**Comment by iamleot** [comment]
Thank you very much @saulpw!

I have now unrelated issues that can be just reproduced by running `python3 -m visidata /tmp/repro.csv`, i.e. I have the following Traceback with commit cc99e73718e45ae1b0ef706500742b22bbf9ff2e:

```

saul.pw/VisiData v3.4dev

opening /tmp/repro.csv as csv
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ".../visidata/visidata/__main__.py", line 3, in <module>
    vd_cli()
  File ".../visidata/visidata/main.py", line 392, in vd_cli
    rc = main_vd()
  File ".../visidata/visidata/main.py", line 350, in main_vd
    run(vd.sheets[0])
  File ".../visidata/visidata/vdobj.py", line 34, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
  File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File ".../visidata/visidata/mainloop.py", line 341, in run
    scr = vd.initCurses()
  File ".../visidata/visidata/extensible.py", line 80, in wrappedfunc
    r = oldfunc(*args, **kwargs)
  File ".../visidata/visidata/mainloop.py", line 314, in initCurses
    vd.drainPendingKeys(scr)
  File ".../visidata/visidata/vdobj.py", line 137, in drainPendingKeys
    scr.timeout(self.get_curses_timeout())
  File ".../visidata/visidata/mainloop.py", line 284, in get_curses_timeout
    vd.numTimeouts += 1
AttributeError: 'VisiData' object has no attribute 'numTimeouts'
```

By doing a `git bisect` it seems that the last "good" commit is bcc565e3a20abfd50d29ad4508c20815617217d6.

Unfortunately I will be asleep and AFK next day but I hope to try to give it a look more in depth in 22 hours or so!

**Comment by iamleot** [comment]
> Thank you very much @saulpw!
> 
> I have now unrelated issues that can be just reproduced by running `python3 -m visidata /tmp/repro.csv`, i.e. I have the following Traceback with commit [cc99e73](https://github.com/saulpw/visidata/commit/cc99e73718e45ae1b0ef706500742b22bbf9ff2e):
> 
> ```
> 
> saul.pw/VisiData v3.4dev
> 
> opening /tmp/repro.csv as csv
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File ".../visidata/visidata/__main__.py", line 3, in <module>
>     vd_cli()
>   File ".../visidata/visidata/main.py", line 392, in vd_cli
>     rc = main_vd()
>   File ".../visidata/visidata/main.py", line 350, in main_vd
>     run(vd.sheets[0])
>   File ".../visidata/visidata/vdobj.py", line 34, in _vdfunc
>     return getattr(visidata.vd, func.__name__)(*args, **kwargs)
>   File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
>     return oldfunc(*args, **kwargs)
>   File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
>     return oldfunc(*args, **kwargs)
>   File ".../visidata/visidata/extensible.py", line 66, in wrappedfunc
>     return oldfunc(*args, **kwargs)
>   File ".../visidata/visidata/mainloop.py", line 341, in run
>     scr = vd.initCurses()
>   File ".../visidata/visidata/extensible.py", line 80, in wrappedfunc
>     r = oldfunc(*args, **kwargs)
>   File ".../visidata/visidata/mainloop.py", line 314, in initCurses
>     vd.drainPendingKeys(scr)
>   File ".../visidata/visidata/vdobj.py", line 137, in drainPendingKeys
>     scr.timeout(self.get_curses_timeout())
>   File ".../visidata/visidata/mainloop.py", line 284, in get_curses_timeout
>     vd.numTimeouts += 1
> AttributeError: 'VisiData' object has no attribute 'numTimeouts'
> ```
> 
> By doing a `git bisect` it seems that the last "good" commit is [bcc565e](https://github.com/saulpw/visidata/commit/bcc565e3a20abfd50d29ad4508c20815617217d6).
> 
> Unfortunately I will be asleep and AFK next day but I hope to try to give it a look more in depth in 22 hours or so!

I have filled #2914 to keep track of that given that it is a separate and unrelated issue.
