### ISSUE TITLE
Get openpyxl error when opening xlsx file where a cell in the table has an emptycell

### ISSUE THREAD

**Issue by dslgr** [saulpw/visidata#1121]
OS: Windows 10 (10.0.19043 Build 19043)
VisiData: v2.6
Python: v3.9.5
openpyxl: v3.0.9
[test_excel_visidata.xlsx](https://github.com/saulpw/visidata/files/7232237/test_excel_visidata.xlsx)
[excel_emptycell_visidata_error.txt](https://github.com/saulpw/visidata/files/7232238/excel_emptycell_visidata_error.txt)

Opening an xlsx file with an empty cell gives this error and then prevents the row with that cell and all lower rows from being read:
Traceback (most recent call last):
  File "/home/dslgr/.local/lib/python3.9/site-packages/visidata/threads.py", line 206, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/dslgr/.local/lib/python3.9/site-packages/visidata/sheets.py", line 940, in reload
    for r in vd.Progress(itsource, gerund='loading', total=0):
  File "/home/dslgr/.local/lib/python3.9/site-packages/visidata/threads.py", line 68, in __iter__
    for item in self.iterable:
  File "/home/dslgr/.local/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 56, in iterload
    yield AttrDict({cell.column_letter:cell for cell in row})
  File "/home/dslgr/.local/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 56, in <dictcomp>
    yield AttrDict({cell.column_letter:cell for cell in row})
AttributeError: 'EmptyCell' object has no attribute 'column_letter'

I attached an example xlsx file but this can easily be recreated with an xlsx file with an empty cell contained within the data. In this example only the first row will be read as the empty cell is in the second row. So the second and third rows aren't read.

I believe this error is related to this issue: https://stackoverflow.com/questions/39596433/get-empty-cell-coordinates-with-openpyxl
When looping through the cells of a row it may be necessary to also count the columns. If a cell value is None to then potentially get the column letter from this function: https://stackoverflow.com/a/23862195
This may also be helpful to reference: https://openpyxl.readthedocs.io/en/stable/api/openpyxl.cell.read_only.html?highlight=column_letter#openpyxl.cell.read_only.EmptyCell

**Comment by anjakefala** [comment]
Thanks for such a thorough bug report @dslgr! Especially grateful for the sample data, and doing preliminary research on the bug.

**Comment by ghost** [comment]
I just hit this after upgrading from 2.4 to 2.6.
A rough hack (not the *correct* solution!) which at least allows tables to load is to change the `iterload` function in line 53 of `/usr/lib/python3/dist-packages/visidata/loaders/xlsx.py` to:

``` python
    def iterload(self):
        worksheet = self.source
        for index, row in enumerate(Progress(worksheet.iter_rows(), total=worksheet.max_row or 0)):
            column_dict = {}
            for cell in row:
                try:
                    column_letter = cell.column_letter
                except AttributeError:
                    column_letter = index
                column_dict[column_letter] = cell
            yield AttrDict(column_dict)
```

**Comment by ghost** [comment]
I just noticed that #1098 contains a [commit](https://github.com/saulpw/visidata/pull/1098/commits/c5eff419db9fecd81567aecaa757c0433e8b7315#) which will fix this issue.

**Comment by anjakefala** [comment]
Thanks to @hoclun-rigsep, who had committed a fix in #1098!

I ported @hoclun-rigsep's fix over to develop, and added a test, using the sample data you kindly provided!

**Comment by jsvine** [comment]
Unfortunately, I'm still getting this error (as of current `develop` branch), I think because `.column_letter` is still referenced elsewhere in the loader:

https://github.com/saulpw/visidata/blob/bcf2ea6da5598618665f277c9a8d1b181f49b605/visidata/loaders/xlsx.py#L42

Opening this test file — [empty-test.xlsx](https://github.com/saulpw/visidata/files/7456962/empty-test.xlsx) — produces this error:

```python
Traceback (most recent call last):
  File "visidata/threads.py", line 206, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "visidata/sheets.py", line 926, in reload
    self.setCols(list(self.optlines(itsource, 'header')))
  File "visidata/loaders/xlsx.py", line 42, in setCols
    column_letters = [x.column_letter for x in headerrows[0].values()]
  File "visidata/loaders/xlsx.py", line 42, in <listcomp>
    column_letters = [x.column_letter for x in headerrows[0].values()]
AttributeError: 'EmptyCell' object has no attribute 'column_letter'
```

**Comment by anjakefala** [comment]
@jsvine Ah! We will merge that fix in with the PR. https://github.com/saulpw/visidata/pull/1098

Thank you for letting me know!

**Comment by anjakefala** [comment]
> Opening this test file — empty-test.xlsx — produces this error:

Hm, I cannot reproduce this on the `develop` branch...

**Comment by jsvine** [comment]
Ah, now working for me, too! Looks like the relevant fix got merged into `develop` a couple of days after I posted. Thanks!

<img width="494" alt="Screen Shot 2021-11-06 at 9 05 16 AM" src="https://user-images.githubusercontent.com/534702/140610641-f4fc6e99-17b3-495b-b9a0-e287ae3f26fd.png">

**Comment by anjakefala** [comment]
Awesome!!

**Comment by TauPan** [comment]
Hm... I have a (non-empty) excel file which gives me "0 rows" when I open the first sheet and afterwards when I press `ctrl-R` I get the error in this issue.

Some excel sheets I *can* open. I'll attach (a very short) one that reproduces this error (also created with the same python code with openpyxl).

Note that in the first sheet (the sheet overview) the `Vulnerabilities` sheet is already listed with `nRows# 0` but in libreoffice the two rows (headers and 1 data row) are shown correctly.

[Vulnerabilities a_b_c_d_e_f_g_h.xlsx](https://github.com/saulpw/visidata/files/7496993/Vulnerabilities.a_b_c_d_e_f_g_h.xlsx)

**Comment by anjakefala** [comment]
@TauPan Are you using the VisiData on the most recent `develop` branch? This fix has not been released yet, and I can open the file fine in `develop` VisiData.

To install develop VisiData, you can run `pip3 install git+https://github.com/saulpw/visidata.git@develop`. But the release should happen very soon (this week), if you are up for waiting.

**Comment by TauPan** [comment]
> @TauPan Are you using the VisiData on the most recent `develop` branch? This fix has not been released yet, and I can open the file fine in `develop` VisiData.
> 
> To install develop VisiData, you can run `pip3 install git+https://github.com/saulpw/visidata.git@develop`. But the release should happen very soon (this week), if you are up for waiting.

I upgraded before commenting (your command  together with `--upgrade`). Did you try the attached file?

**Comment by anjakefala** [comment]
I did! Is this what you expect to see when things are working?

![Screenshot from 2021-11-08 10-39-44](https://user-images.githubusercontent.com/7489659/140798991-b29c8a98-9151-4201-a7b0-06280ca994d1.png)
![Screenshot from 2021-11-08 10-39-55](https://user-images.githubusercontent.com/7489659/140798994-a001b8a1-0528-43fb-beb2-57ca757cd7ab.png)

**Comment by anjakefala** [comment]
If that is what is expected, and you had installed VisiData previously using a different method, it is possible that the old version has stuck around in your environment!

**Comment by TauPan** [comment]
> If that is what is expected, and you had installed VisiData previously using a different method, it is possible that the old version has stuck around in your environment!

Yes, that's the expected result. I'll double check tomorrow if there's an old version sticking around. SFTN!

**Comment by anjakefala** [comment]
@TauPan Some ways that you can try to track down old versions!

If you installed with pip:
`pip list -v | grep visidata`
`(head -1 $(which vd) | sed -e 's/#!//') -m pip show visidata` 

If you installed with homebrew:
`brew info visidata`

If you installed with apt:
`dpkg -L visidata`

**Comment by TauPan** [comment]
Hm, weird. I had to `pip uninstall visidata` and then reinstall from git as [above](https://github.com/saulpw/visidata/issues/1121#issuecomment-963455340), but then it worked.

Thanks again!

**Comment by anjakefala** [comment]
Awesome news! I mean, not awesome that Python does weird environment things, but awesome news that the bug fix is holding!
